### PR TITLE
Conditional logic

### PR DESCRIPTION
**Pull request by ajb**
Opening this PR early since we haven't really talked about how the conditional fields would work in the form renderer context.

@jrubenoff: can you check out the "Conditional" template in `examples/index.html` and lmk what you think? Is anything totally off in terms of structure?

### CODE REVIEW

**Comment by ajb** [comment]
Alright, this is definitely ready for review now.

**Comment by jrubenoff** [comment]
Awesome, thanks for covering that one-form-field-per-page edge case!

Don't think we need to expose "hide" in the front end, at least. I actually found this super confusing... since the text field is the same length and the questions start with the same word, it took me a second to realize the fields were changing, even when I had the source code in front of me.

From an interaction standpoint, we probably want to add `.is_conditional` and `.is_hidden` instead of just toggling `display: none;`. Might want to animate the conditional fields as they appear.

Here's an edge case:

- I type `7` in "Guess a number"
- I type an answer in "Why do you like big numbers?"
- I go back and type `5` in "Guess a number"

Is the answer in "Why do you like big numbers?" still submitted?

**Comment by ajb** [comment]
re hide: i disagree, but its easy enough to experiment with. i recognize
that the example i'm using in the fixtures is pretty wacky.

re interaction, currently we're using jquery .hide and .show. i assumed
that we could add animations via javascript.

re your edge case, the answer is no.

On Thursday, February 12, 2015, Josh Rubenoff <notifications@github.com>
wrote:

> Awesome, thanks for covering that one-form-field-per-page edge case!
>
> Don't think we need to expose "hide" in the front end, at least. I
> actually found this super confusing... since the text field is the same
> length and the questions start with the same word, it took me a second to
> realize the fields were changing, even when I had the source code in front
> of me.
>
> From an interaction standpoint, we probably want to add .is_conditional
> and .is_hidden instead of just toggling display: none;. Might want to
> animate the conditional fields as they appear.
>
> Here's an edge case:
>
>    - I type 7 in "Guess a number"
>    - I type an answer in "Why do you like big numbers?"
>    - I go back and type 5 in "Guess a number"
>
> Is the answer in "Why do you like big numbers?" still submitted?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dobtco/formrenderer-base/pull/26#issuecomment-74179945>
> .
>


-- 
Adam Becker
(951) 9-BECKER
@AdamJacobBecker

**Comment by jrubenoff** [comment]
In the edge case above, what are your thoughts on clearing the input when the user hides it?

**Comment by ajb** [comment]
So the current behavior is that hidden fields will not get submitted. However, we do not currently clear the fields when they are hidden.

What I think you are asking is: do I think we should clear fields when they are hidden? 

My answer would be "no", primarily because a field might be hidden and then shown in quick succession (imagine accidentally hitting a radio button..) and it would suck for a user to lose their input.

**Comment by jrubenoff** [comment]
Sounds good to me.

**Pull request merged**
