### PR TITLE
first take at better validations

### LINKED ISSUE #56: Multi-page validation behavior
### Pages with validation errors should *always* have an indication of these errors

Whenever a user leaves a page with validation errors, we should display the circled page number for that page in red. This should persist across refreshes, reloads, and returning to a draft.

### There should be *one* behavior for switching pages

Switching pages with the circled page numbers and switching pages with the bottom status bar buttons should have the same behavior. If we're going to allow users to navigate away from a page that has validation errors, they should be able to do it via either navigation vector.

From chat:

> adam
i think we should change the behavior to only validate when submitting, not paginating
and that fields should also be validated on `blur()`
so that as you're filling out a form, you get instant validation of any mistakes you're making
instead of waiting until you change pages

### PR DESCRIPTION
**Pull request by ajb**
closes #56. not yet ready for merge, needs review, tests, and refactoring.

@aviv + @jrubenoff, can you look at this and tell me what you think? I've tried to cover the stuff I talked about in https://github.com/dobtco/formrenderer-base/issues/56#issuecomment-87062209, but I'm sure there are some weird edge cases that I'm not accounting for...

### CODE REVIEW

**Comment by ajb** [comment]
Actually, let me provide some more detail on how this works, so that y'all will have a bit easier time giving feedback. I've done everything from my comment earlier:

> - Run validations (except presence validation) when a field is blurred
> - Don't ever validate when switching between pages
> - Run all validations when clicking the "Submit" button
> - Add a "take me to first error" link to the error_alert

And also:

- When a field is in an error state and its value is changed, it validates immediately:

img

- When a field is in an error state and its error _changes_, it is only shown the next time it's blurred:

img

Those are the main "gotchas", I think. Lmk what y'all think.

**Comment by aviv** [comment]
- If you delete the text in a required field and leave it blank, then blur, you don't get a validation error until you try to submit.

**Comment by ajb** [comment]
@aviv: that's the intended behavior, at least as I designed it. It's the same behavior as when you blur a required field.

**Comment by aviv** [comment]
Got it, we're treating presence validations differently.

**Comment by aviv** [comment]
So, I think this is looking good. Not sure about how we're persisting these validation errors across page reloads because response data isn't getting saved.

**Comment by ajb** [comment]
Nothing has changed in that regard -- just pass the `validateImmediately`
option and you'll be able to see what happens.

On Mon, Apr 6, 2015 at 4:15 PM, Aviv Nitsan <notifications@github.com>
wrote:

> So, I think this is looking good. Not sure about how we're persisting
> these validation errors across page reloads because response data isn't
> getting saved.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dobtco/formrenderer-base/pull/58#issuecomment-90227263>
> .
>



-- 
Adam Becker
(951) 9-BECKER
@AdamJacobBecker

**Comment by jrubenoff** [comment]
Looking good.

There's some awkward behavior when you trigger an error state in an input, and then press the "Next page" button. The error appears when the user presses the button, but the page changes when they release their finger.

Maybe don't trigger the error when the user is switching pages?

**Comment by ajb** [comment]
Yes, I think I can mitigate against that behavior.

**Comment by ajb** [comment]
@jrubenoff: can I get a final review? I fixed the issue you brought up, wrote some tests, and refactored a tiny bit.

**Comment by jrubenoff** [comment]
When you fill out a field with an error, go to the next page, then return to the previous page, the error doesn't appear even though the field is blurred.

**Comment by ajb** [comment]
> When you fill out a field with an error, go to the next page, then return to the previous page, the error doesn't appear even though the field is blurred.

So this is happening due to our special handling of the "next page" button, based on your comment from earlier:

> There's some awkward behavior when you trigger an error state in an input, and then press the "Next page" button. The error appears when the user presses the button, but the page changes when they release their finger.

How vital is it that we handle this edge case?

**Comment by jrubenoff** [comment]
I'm good with merging this now if it's a huge hassle, but I'm curious whether anyone has a better idea to resolve this.

The outcomes here:

- Our error validation should behave consistently
- Nothing happens that the user could construe as a UI glitch

Any other ways you can think of achieving those? Having a text or paragraph field with character limits as the last field on a form / page doesn't seem like an edge case to me.

**Comment by ajb** [comment]
FWIW, a lot of client-side validation libraries have similar issues, so we're not alone in this problem.

In terms of implementation, the problem is that the `blur` event fires before the `click` event does. Actually, `blur` fires when the mouse is pressed, and `click` fires when it's released, so there are potentially hundreds of milliseconds in between us showing an error and the page changing.

I just added a commit that goes even _further_ to hack around this issue, so go ahead and test it out.

If it works, I'm comfortable merging it for now, especially since I wrote a test for it, but it might not be the best long-term solution since it's more hacky than I'd like.

**Comment by jrubenoff** [comment]
Alright. Looks good... let's make sure to figure out a better solution in the future.

**Comment by ajb** [comment]
note to self: try document.mouseup before merging.

On Tuesday, April 7, 2015, Josh Rubenoff <notifications@github.com> wrote:

> Alright. Looks good... let's make sure to figure out a better solution in
> the future.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dobtco/formrenderer-base/pull/58#issuecomment-90773981>
> .
>


-- 
Adam Becker
(951) 9-BECKER
@AdamJacobBecker

**Pull request merged**
