### PR TITLE
fix onBlur validation

### PR DESCRIPTION
**Pull request by ajb**
turns out e.relatedTarget is far from a standard. instead, we'll use a timeout and document.activeElement to grab the newly-activated element.

cf https://github.com/dobtco/screendoor-v2/issues/1838#issuecomment-103659992

@kariannemah and @jrubenoff can you test this out?

### CODE REVIEW

**Comment by jrubenoff** [comment]
This was broken in Firefox, right? Tested, looks good.

**Comment by ajb** [comment]
Yes, was broken in Firefox and perhaps even Safari, IE, others. Unless you just tested in those browsers, @kariannemah will you do so?

**Comment by kariannemah** [comment]
I'll test it now.

**Comment by kariannemah** [comment]
All good on Firefox, Chrome, Safari. Trying to test it in IE 10 with Browserstack, but I can't seem to connect to `examples/index.html`: http://take.ms/yPHyq

**Comment by ajb** [comment]
Thanks. Browserstack can't access your local filesystem from it's VMs... you need to configure local testing: 

img

Anyway, I just tested and it works in IE10 and degrades alright on IE9.

**Comment by kariannemah** [comment]
Ah, duly noted. I was accustomed to "test[ing] an internal URL" with `http://screendoor.dobt.dev` and /splash running on `http://localhost:4000/`.

**Pull request merged**
