### PR TITLE
Trigger an autosave when adding or removing entries, or skipping groups.

### PR DESCRIPTION
**Pull request by vlymar**
Adding/removing entries in formrenderer modifies the `@entries` attribute. Nothing listens for changes no that attribute, so I manually trigger `responsesChanged` when entries are added, removed, or the group is skipped altogether.

This fixes a bug where if you remove entries or skip the group then proceed to preview the submission, the entries still appear as a part of your submission (because no save happened).

Screendoor tracking issue: https://github.com/dobtco/screendoor-v2/issues/4799

### CODE REVIEW

**Comment by vlymar** [comment]
@kariannemah, this PR assumes that you were seeing that bug where entries were still appearing in the preview even though you deleted them was happening because adding/removing entries or clicking "skip" on the group don't trigger autosave. So if thats the last thing you do before you click preview, whatever was the last save state will appear on the preview page. Same for page reloads. So this PR just forces the save to happen when you add/remove entries or skip.

Can you confirm that you never saw this behavior when you had the form save after clicking remove? E.g.
1. remove entry from the group
2. edit some other value on the form to trigger an autosave

sorry for the word soup

**Comment by kariannemah** [comment]
>Can you confirm that you never saw this behavior when you had the form save after clicking remove? E.g.
>
>remove entry from the group
>edit some other value on the form to trigger an autosave

That's correct. I only refreshed the page immediately after removing an entry (or multiple entries) from the group.

**Comment by vlymar** [comment]
@drusepth, I believe we agreed `1.3.0` would be the official release of formrenderer. I think after we merge this and https://github.com/dobtco/formrenderer-base/pull/166#pullrequestreview-84933666 to master we can tag master as 1.3.0?

**Comment by drusepth** [comment]
Changes look good and we are good to tag&merge 1.3.0 as soon as both this and that PR are merged. 🚢

**Pull request merged**
