### PR TITLE
Add icons to formbuilder labels

### PR DESCRIPTION
**Pull request by jrubenoff**
Adds icons to field labels in Screendoor's form builder.

screen shot 2017-07-25 at 3 47 22 pm

Edit: Not sure why the build is failing...

### CODE REVIEW

**Comment by vlymar** [comment]
@jrubenoff, any idea why thousands of lines of code got deleted as a part of the build here? https://github.com/dobtco/formrenderer-base/pull/146/commits/628a1029e2ef7c9464f5dc0a54dfaf28cd75642b#diff-49bf7afef736b8fa7016b275a05bf3b8

Can you try building again and see if those lines are restored?

**Comment by vlymar** [comment]
> I think this is due to trouble I was having while bootstrapping the repo. We could troubleshoot later together if you’d like

https://dobt.slack.com/archives/C024ZNYSG/p1501109094009671?thread_ts=1501108732.899265&cid=C024ZNYSG

**Comment by vlymar** [comment]
@drusepth, it looks like something is wrong with josh's dev environment, causing his build to fail.

You have the closest thing to a functional JS environment right now, could you please build the repo and commit the changes when you have a moment?

**Comment by vlymar** [comment]
Besides the failed code build, the code change itself looks fine.

**Comment by drusepth** [comment]
Code looks good to me, and it looks like a rebuild fixed the tests as well.

**Comment by jrubenoff** [comment]
Will merge once the Screendoor PR is approved!

**Comment by vlymar** [comment]
this looks good to merge to me.

@drusepth, have you been generating releases by just adding a git tag and running `script/release X.X.X` or is it more complicated then that?

**Comment by drusepth** [comment]
@vlymar Actually, the `script/release X.X.X` creates and pushes the git tag as well. 

Relevant code from `script/release`:

```
grunt all
grunt test
git commit -am "release $version"
git tag $version
git push origin master --tags
grunt s3:version
```
It'll also push properly to rails-assets, so `script/release X.X. X` on master should be all you need to do for a full release. 

(For major version changes there is one other change to make in the URL [changing /1/ to /2/ in path config], but it's not necessary for minor/patch updates.)

**Comment by jrubenoff** [comment]
@vlymar, please merge this if you're 👍 with it.

**Pull request merged**
