### PR TITLE
Revert character count styles, but make them easily overrideable

### LINKED ISSUE #59: Improved character count
img

### PR DESCRIPTION
**Pull request by ajb**
closes #59

I wanted to add the absolutely-positioned character count, but then I looked at all of the different sizes of text and paragraph fields that it would have to support:

img

I think this solution is better. It reverts the basic behavior to an inline count, and makes it easier for us to override this in our implementations, e.g. respondent view. The solution inside of this repository needs to be fairly unopinionated so that it works well in all implementations.

img

If there's anything better we can do _without_ a bunch of custom styles, I'm all ears. (The one thing that comes to mind would be better copy, maybe.) Otherwise, it should be simple to override this inside of Screendoor. (I can handle that.)

### CODE REVIEW

**Comment by jrubenoff** [comment]
Can you explain a little more why supporting all those input sizes is an issue? The current implementation simply fixes the character counter to the right side of the input... by design, it shouldn't matter how wide it is.

The only custom styles involve adding a wrapper `div` to the input, and positioning the counter absolutely. All the other CSS in #59 is related to appearance and can be excluded if necessary.

Also, this change was originally requested to keep the character counter in a consistent place. It is difficult to visually locate the character counter in the middle of a paragraph. Any overrides we make would have to keep the character counter in a consistent location for usability's sake.

**Comment by ajb** [comment]
Apologies, I did a crappy job of explaining my thinking.

- The styles in formrenderer-base need to adapt to most host websites without requiring manual CSS overrides from the implementer
- We don't know how much padding the host website's inputs/textareas have

I'm up for trying something like this:

img

But then we run into a couple issues:

- Do we add padding so that the counter doesn't block the view of the text in the input?
- Alternatively, we could make the counter transparent, but I don't think that would work very well...
- The "resize" anchor for the textareas is now hidden

Maybe you have a different solution in mind?

**Comment by jrubenoff** [comment]
What if we floated them to the right, directly below the input?

**Comment by ajb** [comment]
That's actually what I was thinking of why I wrote my earlier comment -- what happens here?

img

**Comment by ajb** [comment]
This is precisely why I'd rather implement this _outside_ of the core lib ;)

On Tue, May 5, 2015 at 2:47 PM, Josh Rubenoff <notifications@github.com>
wrote:

> The character limit could be on a new line, below the counter.
>
> [image: screen shot 2015-05-05 at 11 47 16 am]
> <https://cloud.githubusercontent.com/assets/1328849/7480300/84d93bc0-f31c-11e4-8fdd-89f9d49af180.png>
>
> Visually it's a little awkward, but definitely more usable.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dobtco/formrenderer-base/pull/69#issuecomment-99178023>
> .
>



-- 
Adam Becker
(951) 9-BECKER
@AdamJacobBecker

**Comment by ajb** [comment]
This is also kinda problematic in respondent view: (already filed over there)

img

Here's what bottom-floated counters look like. I don't think this is viable:

img

Here's my new proposal for implementing inside of this lib, which is a bit more minimal:

img

We can still override respondent view as much as we want.

Is this alright?

**Comment by jrubenoff** [comment]
Cool. Let's keep the bubble to the character counter so that I don't have to manually hide the parens every time:

screen shot 2015-05-20 at 10 30 16 am

**Pull request merged**
