### PR TITLE
Time validation defaults

### PR DESCRIPTION
**Pull request by drusepth**
If a user enters invalid data for hour or minute fields, we want to show them a validation error instead of defaulting it to zero. 

This PR keeps the functionality of defaulting invalid second-hand fields to zero, so people can choose to leave that field blank if they choose. Let me know if we should change this also (it's a quick change), but I figured that would be a little better UX than requiring the seconds field when I imagine most people care more about hour/minute and would just enter zero/blank in seconds anyway.

### CODE REVIEW

**Comment by kariannemah** [comment]
>This PR keeps the functionality of defaulting invalid second-hand fields to zero, so people can choose to leave that field blank if they choose. 

Fine with me. 👍

**Comment by vlymar** [comment]
code change looks fine to me.

do we have any idea why this changed after the big refactor?

**Comment by drusepth** [comment]
There's not an indication in the code to whether it was intentional or not, but my best guess would be that we were defaulting seconds originally (perhaps) and someone thought it'd make sense to default other values like minutes also and got a bit too copy-paste happy. I can definitely see the merit in thinking "if someone wants 4pm they might just enter 4 in the hour cell and leave the rest empty", but defaulting hours to 0 seems like a mistake.

**Comment by drusepth** [comment]
This was included and merged in with #156.

**Pull request closed without merging**
