### PR TITLE
add fieldset / legend pattern

### PR DESCRIPTION
**Pull request by ajb**
cf #96

Converts the following fields to use `<fieldset>` and `<legend>`:

- Price
- Address
- Checkboxes
- Radio
- Time
- Date

## Todo

- [x] @jrubenoff: review?
- [ ] Test in all browsers (ensure that browsers aren't setting ugly default styles for the new elements...)
- [x] Test with different libraries installed on host pages

## After merging

- [ ] Release a new _minor_ version

### CODE REVIEW

**Comment by jrubenoff** [comment]
Your changes look good! A few more things we need:

- Let's convert the File input to a fieldset, too, since we let respondents upload multiple files:

screen shot 2016-03-07 at 3 21 43 pm

- We need to add visually hidden labels in a few places:

screen shot 2016-03-07 at 3 24 27 pm

screen shot 2016-03-07 at 3 27 30 pm

How can we do this in a way that requires the fewest overrides? Using `visibility: hidden`?

Also remember that we'll need to update styles in both Screendoor and respondent view after merging.

**Comment by ajb** [comment]
Sorry, I should have mentioned: map markers and tables still have some a11y issues, which is why I left the original issue open. I know we hate those field types, so I didn't want to spend a bunch of effort on them... 

Also, I already added `aria-label` to the AM/PM input, which I kinda prefer to a visually hidden `<label>` element. Any reason it matters one way or the other?

:+1: on file input, I'll get that done once we're set on these other things.

**Comment by ajb** [comment]
Oops, didn't read your whole comment.

> How can we do this in a way that requires the fewest overrides? Using visibility: hidden?

`aria-label`?

**Comment by jrubenoff** [comment]
`aria-label` works!

**Comment by ajb** [comment]
Rebased.

Tested for weird legend styles in IE9, IE11, FF Latest (Win), Safari Latest (Win).

**Pull request merged**
